## Listing 5.1 Instantiating a small convnet

In [1]:
from tensorflow.keras import layers
from tensorflow.keras import models


model = models.Sequential()

model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

In [2]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
Total params: 55,744
Trainable params: 55,744
Non-traina

# Listing 5.2 Adding a classifier on top of the **convnet**

In [5]:
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [4]:
3*3*64

576

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
 flatten (Flatten)           (None, 576)               0

# Listing 5.3 Training the convnet on MNIST images

In [7]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [9]:
print(train_images.shape, train_labels.shape)

(60000, 28, 28) (60000,)


In [10]:
print(test_images.shape, test_labels.shape)

(10000, 28, 28) (10000,)


In [11]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [13]:
train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=5, batch_size=64)

Epoch 1/5
938/938 [==============================] - 14s 5ms/step - loss: 0.1827 - accuracy: 0.9431
Epoch 2/5
938/938 [==============================] - 4s 5ms/step - loss: 0.0471 - accuracy: 0.9854
Epoch 3/5
938/938 [==============================] - 4s 4ms/step - loss: 0.0323 - accuracy: 0.9897
Epoch 4/5
938/938 [==============================] - 4s 4ms/step - loss: 0.0249 - accuracy: 0.9924
Epoch 5/5
938/938 [==============================] - 5s 5ms/step - loss: 0.0186 - accuracy: 0.9943


# Testing

In [14]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)
print(test_loss)

313/313 [==============================] - 1s 4ms/step - loss: 0.0267 - accuracy: 0.9918
0.9918000102043152
0.026713721454143524


# prediction for output

In [15]:
p = model.predict(test_images )
p

313/313 [==============================] - 1s 2ms/step


array([[3.3478594e-14, 1.8737285e-10, 2.8889890e-09, ..., 1.0000000e+00,
        7.4219179e-13, 6.8048761e-10],
       [2.3374785e-06, 6.0269354e-09, 9.9999762e-01, ..., 9.6330431e-15,
        4.7285571e-09, 3.0292526e-15],
       [1.3212144e-09, 9.9999905e-01, 2.4768991e-09, ..., 6.4351866e-08,
        1.5264740e-07, 4.2136366e-09],
       ...,
       [6.7058027e-15, 6.5257098e-11, 4.0231283e-14, ..., 1.5144461e-09,
        1.4411921e-08, 5.6753935e-10],
       [1.1114609e-14, 7.4875442e-15, 1.4602277e-17, ..., 1.3715491e-15,
        6.0391585e-09, 1.5520706e-16],
       [7.2883417e-08, 9.7473463e-10, 3.8129260e-09, ..., 4.6027453e-15,
        1.8683160e-08, 3.0006830e-12]], dtype=float32)

In [16]:
p[0]

array([3.3478594e-14, 1.8737285e-10, 2.8889890e-09, 1.2930533e-10,
       3.1561190e-12, 1.0652604e-11, 6.0199168e-17, 1.0000000e+00,
       7.4219179e-13, 6.8048761e-10], dtype=float32)

In [17]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)